#!/bin/sh
#
# $FreeBSD: releng/11.3/etc/rc.d/dsmc 298514 2016-04-23 16:10:54Z lme $
#

# PROVIDE: dsmc
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name=dsmc
rcvar=dsmc_enable

desc="Start scheduler for spectrum protect"

start_cmd='/compat/linux/bin/bash -c "export DSM_DIR=/compat/linux/etc/tsm; /compat/linux/bin/dsmc sched &"'

stop_cmd=':'

load_rc_config $name

run_rc_command "$1"
