#!/bin/sh
#
# $FreeBSD: releng/11.3/etc/rc.d/dsmc 298514 2016-04-23 16:10:54Z lme $
#

# PROVIDE: dsmc
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name=dsmc
rcvar=dsmc_enable

desc="Start scheduler for spectrum protect"

start_precmd=dsmc_precmd

command="/compat/linux/bin/${name}"

command_args="sched"

pidfile="/var/run/${name}.pid"

stop_cmd='kill -9 `cat /var/run/${name}.pid`'


dsmc_precmd()
{
	ln -s /compat/linux/opt/tivoli/tsm/client/ba/bin/EN_US /compat/linux/etc/tsm/EN_US
	export DSM_DIR=/compat/linux/etc/tsm
}


load_rc_config $name

run_rc_command "$1"
